from enum import StrEnum


class RunStatus(StrEnum):
    QUEUED = "QUEUED"
    VALIDATING = "VALIDATING"
    DECOMPOSING = "DECOMPOSING"
    RESEARCHING = "RESEARCHING"
    EXTRACTING = "EXTRACTING"
    ANALYZING_PROVENANCE = "ANALYZING_PROVENANCE"
    SCORING = "SCORING"
    SYNTHESIZING = "SYNTHESIZING"
    AUDITING = "AUDITING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class InputType(StrEnum):
    CLAIM = "CLAIM"
    ARTICLE_URL = "ARTICLE_URL"
    ARTICLE_TEXT = "ARTICLE_TEXT"
    QUOTE = "QUOTE"
    PARAPHRASE = "PARAPHRASE"
    UPLOADED_DOCUMENT = "UPLOADED_DOCUMENT"


class ResearchDepth(StrEnum):
    QUICK = "QUICK"
    STANDARD = "STANDARD"
    DEEP = "DEEP"


class SourceType(StrEnum):
    PRIMARY = "PRIMARY"
    OFFICIAL_SELF_REPORT = "OFFICIAL_SELF_REPORT"
    INDEPENDENT_ANALYSIS = "INDEPENDENT_ANALYSIS"
    SECONDARY_REPORT = "SECONDARY_REPORT"
    DERIVATIVE_REPORT = "DERIVATIVE_REPORT"
    OPINION = "OPINION"
    UNKNOWN = "UNKNOWN"


class AccessStatus(StrEnum):
    PENDING = "PENDING"
    FETCHED = "FETCHED"
    INACCESSIBLE = "INACCESSIBLE"
    PAYWALLED = "PAYWALLED"
    BOT_BLOCKED = "BOT_BLOCKED"
    UNSUPPORTED = "UNSUPPORTED"
    FAILED = "FAILED"


class EvidenceStance(StrEnum):
    STRONGLY_CONTRADICTS = "STRONGLY_CONTRADICTS"
    PARTIALLY_CONTRADICTS = "PARTIALLY_CONTRADICTS"
    NEUTRAL = "NEUTRAL"
    PARTIALLY_SUPPORTS = "PARTIALLY_SUPPORTS"
    STRONGLY_SUPPORTS = "STRONGLY_SUPPORTS"


class DependencyRelationship(StrEnum):
    CITES = "CITES"
    REPUBLISHES = "REPUBLISHES"
    QUOTES = "QUOTES"
    DERIVES_FROM = "DERIVES_FROM"
    USES_SAME_DATA = "USES_SAME_DATA"
    POSSIBLE_DUPLICATE = "POSSIBLE_DUPLICATE"


class FeedbackCategory(StrEnum):
    CORRECTION = "CORRECTION"
    MISSED_EVIDENCE = "MISSED_EVIDENCE"
    APPEAL = "APPEAL"
    BROKEN_CITATION = "BROKEN_CITATION"


class ExportFormat(StrEnum):
    JSON = "JSON"
