import type { ReportRecord } from "@/lib/report-types";

export const mockedRunId = "run_mock_2026_06_25_standard";

export const mockedReport: ReportRecord = {
  runId: mockedRunId,
  status: "COMPLETED",
  title: "Citywide transit ridership recovery claim",
  inputType: "CLAIM",
  researchDepth: "STANDARD",
  submittedAt: "2026-06-25T18:42:00-04:00",
  evidenceReviewedAt: "2026-06-25T21:18:00-04:00",
  evidenceTimestampText:
    "Evidence reviewed as of June 25, 2026 at 9:18 PM America/Toronto. New evidence or corrections may change this assessment.",
  verdict: "Partially supported with unresolved context",
  verdictSummary:
    "Available evidence supports the direction of the ridership increase, but the exact percentage depends on baseline selection and excludes two commuter rail lines that were described in the submitted claim.",
  limitations: [
    "One requested board memo was inaccessible at review time and is listed separately.",
    "The public dashboard reports weekly averages, while the submitted claim used a monthly phrasing.",
    "A causal explanation about fare policy was not directly supported by the reviewed sources.",
  ],
  scoreRecords: [
    { key: "evidence_support", label: "Evidence Support", value: 72, maxValue: 100, source: "calculation_record", calculationId: "calc_support_overall" },
    { key: "attribution_support", label: "Attribution Support", value: 100, maxValue: 100, source: "calculation_record", calculationId: "calc_attribution_not_applicable" },
    { key: "quote_fidelity", label: "Quote Fidelity", value: 100, maxValue: 100, source: "calculation_record", calculationId: "calc_quote_not_applicable" },
    { key: "verdict_confidence", label: "Verdict Confidence", value: 68, maxValue: 100, source: "calculation_record", calculationId: "calc_confidence" },
    { key: "source_independence", label: "Source Independence", value: 61, maxValue: 100, source: "calculation_record", calculationId: "calc_independence" },
    { key: "context_completeness", label: "Context Completeness", value: 58, maxValue: 100, source: "calculation_record", calculationId: "calc_context" },
  ],
  evidenceBalanceRecords: [
    {
      atomicClaimId: "claim_ridership_direction",
      claimLabel: "Ridership rose",
      supportingAdjustedWeight: 2.41,
      contradictingAdjustedWeight: 0.22,
      source: "calculation_record",
      calculationId: "calc_claim_direction",
    },
    {
      atomicClaimId: "claim_exact_percentage",
      claimLabel: "Increase was 35 percent",
      supportingAdjustedWeight: 1.12,
      contradictingAdjustedWeight: 0.74,
      source: "calculation_record",
      calculationId: "calc_claim_percentage",
    },
    {
      atomicClaimId: "claim_fare_cause",
      claimLabel: "Fare policy caused increase",
      supportingAdjustedWeight: 0.38,
      contradictingAdjustedWeight: 0.45,
      source: "calculation_record",
      calculationId: "calc_claim_cause",
    },
  ],
  confidenceComponentRecords: [
    { key: "coverage", label: "Coverage", value: 70, maxValue: 100, source: "calculation_record", calculationId: "calc_confidence" },
    { key: "quality", label: "Average Quality", value: 76, maxValue: 100, source: "calculation_record", calculationId: "calc_confidence" },
    { key: "independence", label: "Independence", value: 61, maxValue: 100, source: "calculation_record", calculationId: "calc_confidence" },
    { key: "consistency", label: "Consistency", value: 64, maxValue: 100, source: "calculation_record", calculationId: "calc_confidence" },
    { key: "primary_access", label: "Primary Access", value: 80, maxValue: 100, source: "calculation_record", calculationId: "calc_confidence" },
  ],
  coverageRecords: [
    { key: "adequate", label: "Adequate Evidence", value: 3, maxValue: 5, source: "calculation_record", calculationId: "calc_coverage" },
    { key: "insufficient", label: "Insufficient Evidence", value: 1, maxValue: 5, source: "calculation_record", calculationId: "calc_coverage" },
    { key: "inaccessible_impact", label: "Inaccessible Impact", value: 1, maxValue: 5, source: "calculation_record", calculationId: "calc_coverage" },
  ],
  atomicClaims: [
    {
      id: "claim_ridership_direction",
      claimText: "Citywide transit ridership increased in the latest reported month.",
      claimType: "numerical trend",
      importanceWeight: 3,
      finalLabel: "Supported",
      supportScore: 91,
      confidenceScore: 78,
      contextCompleteness: 74,
      gaps: ["Weekly and monthly reporting windows differ."],
    },
    {
      id: "claim_exact_percentage",
      claimText: "The increase was 35 percent compared with the same month last year.",
      claimType: "percentage comparison",
      importanceWeight: 3,
      finalLabel: "Partially supported",
      supportScore: 60,
      confidenceScore: 66,
      contextCompleteness: 54,
      gaps: ["Commuter rail lines were omitted from the dashboard denominator."],
    },
    {
      id: "claim_fare_cause",
      claimText: "The fare-free pilot caused the increase.",
      claimType: "causal claim",
      importanceWeight: 2,
      finalLabel: "Not verified",
      supportScore: 46,
      confidenceScore: 49,
      contextCompleteness: 43,
      gaps: ["No direct public evaluation isolated fare policy from service restoration."],
    },
  ],
  sources: [
    {
      id: "source_dashboard",
      title: "Monthly ridership dashboard",
      publisher: "City Transit Authority",
      domain: "transit.example.gov",
      sourceType: "PRIMARY",
      accessStatus: "FETCHED",
      retrievedAt: "2026-06-25T20:54:21-04:00",
      parserName: "trafilatura",
      parserVersion: "2.0.0",
      snapshotId: "snap_dashboard_20260625",
      retrievalReason: "Primary public dashboard for monthly and weekly ridership totals.",
    },
    {
      id: "source_minutes",
      title: "Transit board meeting minutes",
      publisher: "City Transit Board",
      domain: "board.example.gov",
      sourceType: "PRIMARY",
      accessStatus: "FETCHED",
      retrievedAt: "2026-06-25T21:02:10-04:00",
      parserName: "pymupdf",
      parserVersion: "1.26.0",
      snapshotId: "snap_minutes_20260625",
      retrievalReason: "Board discussion of ridership context and pilot program scope.",
    },
    {
      id: "source_local_story",
      title: "Transit use rebounds downtown",
      publisher: "Metro Ledger",
      domain: "metroledger.example",
      sourceType: "SECONDARY_REPORT",
      accessStatus: "FETCHED",
      retrievedAt: "2026-06-25T21:08:44-04:00",
      parserName: "beautifulsoup",
      parserVersion: "4.13.0",
      snapshotId: "snap_story_20260625",
      retrievalReason: "Independent reporting that cites the public dashboard and interviews planners.",
    },
    {
      id: "source_board_memo",
      title: "Fare pilot evaluation memo",
      publisher: "City Transit Authority",
      domain: "transit.example.gov",
      sourceType: "PRIMARY",
      accessStatus: "PAYWALLED",
      retrievedAt: null,
      parserName: null,
      parserVersion: null,
      snapshotId: null,
      retrievalReason: "Potential primary evaluation of the fare-free pilot.",
      inaccessibleReason: "The linked memo returned a restricted access page during retrieval.",
    },
  ],
  evidenceItems: [
    {
      id: "evidence_dashboard_total",
      atomicClaimId: "claim_ridership_direction",
      sourceId: "source_dashboard",
      passageId: "passage_dashboard_4",
      stance: "STRONGLY_SUPPORTS",
      stanceValue: 1,
      adjustedWeight: 0.88,
      quality: {
        relevance: 0.96,
        directness: 0.94,
        authority: 0.9,
        transparency: 0.82,
        temporalFit: 0.9,
        extractionCertainty: 0.95,
        dependencyMultiplier: 1,
      },
      excerpt:
        "System ridership averaged 1.42 million weekday trips in May 2026, up from 1.09 million in May 2025 on the same bus and subway services.",
      passageLocator: "Dashboard table, May 2026, rows 4-6",
      citationStatus: "accepted",
    },
    {
      id: "evidence_minutes_scope",
      atomicClaimId: "claim_exact_percentage",
      sourceId: "source_minutes",
      passageId: "passage_minutes_12",
      stance: "PARTIALLY_CONTRADICTS",
      stanceValue: -0.5,
      adjustedWeight: 0.62,
      quality: {
        relevance: 0.84,
        directness: 0.76,
        authority: 0.86,
        transparency: 0.72,
        temporalFit: 0.82,
        extractionCertainty: 0.9,
        dependencyMultiplier: 1,
      },
      excerpt:
        "The dashboard excludes commuter rail and airport express services, which remain reported under a separate ridership series.",
      passageLocator: "Board minutes, page 7",
      citationStatus: "accepted",
    },
    {
      id: "evidence_story_cause",
      atomicClaimId: "claim_fare_cause",
      sourceId: "source_local_story",
      passageId: "passage_story_8",
      stance: "NEUTRAL",
      stanceValue: 0,
      adjustedWeight: 0.18,
      quality: {
        relevance: 0.58,
        directness: 0.42,
        authority: 0.52,
        transparency: 0.61,
        temporalFit: 0.78,
        extractionCertainty: 0.88,
        dependencyMultiplier: 0.35,
      },
      excerpt:
        "Officials said several factors may explain the rebound, including downtown employment, fare policy, and service frequency.",
      passageLocator: "Article section 'What changed'",
      citationStatus: "accepted",
    },
  ],
  inaccessibleSources: [
    {
      id: "source_board_memo",
      title: "Fare pilot evaluation memo",
      publisher: "City Transit Authority",
      domain: "transit.example.gov",
      sourceType: "PRIMARY",
      accessStatus: "PAYWALLED",
      retrievedAt: null,
      parserName: null,
      parserVersion: null,
      snapshotId: null,
      retrievalReason: "Potential primary evaluation of the fare-free pilot.",
      inaccessibleReason: "The linked memo returned a restricted access page during retrieval.",
    },
  ],
  calculations: [
    {
      id: "calc_support_overall",
      formulaName: "weighted_evidence_support",
      formulaText: "100 * P / (P + N)",
      inputs: { supporting_weight: "3.91", contradicting_weight: "1.51" },
      result: { evidence_support: "72.14" },
      units: "percent",
      decimalContext: { precision: 28, rounding: "ROUND_HALF_EVEN" },
      auditStatus: "passed",
    },
    {
      id: "calc_confidence",
      formulaName: "verdict_confidence",
      formulaText: "0.30COV + 0.25QUAL + 0.20IND + 0.15CONS + 0.10PRI - penalties",
      inputs: { coverage: 70, quality: 76, independence: 61, consistency: 64, primary_access: 80, penalties: 2 },
      result: { confidence: 68 },
      units: "score",
      decimalContext: { precision: 28, rounding: "ROUND_HALF_EVEN" },
      auditStatus: "passed",
    },
    {
      id: "calc_attribution_not_applicable",
      formulaName: "attribution_support_applicability",
      formulaText: "plain factual claims without alleged speaker attribution are marked not applicable",
      inputs: { input_type: "CLAIM", speaker_attribution_present: "false" },
      result: { attribution_support_display_value: "100", applicability: "not_applicable" },
      units: "display_score",
      decimalContext: { precision: 28, rounding: "ROUND_HALF_EVEN" },
      auditStatus: "passed",
    },
    {
      id: "calc_quote_not_applicable",
      formulaName: "quote_fidelity_applicability",
      formulaText: "quote fidelity is omitted for non-quote inputs and surfaced as not applicable",
      inputs: { input_type: "CLAIM", exact_quote_present: "false" },
      result: { quote_fidelity_display_value: "100", applicability: "not_applicable" },
      units: "display_score",
      decimalContext: { precision: 28, rounding: "ROUND_HALF_EVEN" },
      auditStatus: "passed",
    },
    {
      id: "calc_claim_percentage",
      formulaName: "claim_evidence_balance",
      formulaText: "supporting_adjusted_weight and contradicting_adjusted_weight grouped by atomic_claim_id",
      inputs: { atomic_claim_id: "claim_exact_percentage", supporting_items: 2, contradicting_items: 1 },
      result: { supporting_adjusted_weight: "1.12", contradicting_adjusted_weight: "0.74" },
      units: "adjusted_weight",
      decimalContext: { precision: 28, rounding: "ROUND_HALF_EVEN" },
      auditStatus: "passed",
    },
  ],
  methodology: {
    methodologyVersion: "elara-methodology-1.0",
    workflowVersion: "workflow-mock-0.2",
    scoringVersion: "scoring-formulas-1.0",
    promptVersions: {
      intake: "intake-v0.1",
      planner: "planner-v0.1",
      synthesis: "synthesis-v0.1",
    },
    modelVersions: {
      intake: "deepseek-chat",
      evidence_classification: "deepseek-chat",
      synthesis: "deepseek-reasoner",
    },
    parserVersions: {
      trafilatura: "2.0.0",
      beautifulsoup: "4.13.0",
      pymupdf: "1.26.0",
    },
    retrievalConfigVersion: "retrieval-policy-1.0",
  },
  sourceGraph: {
    nodes: [
      { id: "cluster_primary", type: "cluster", label: "Official ridership records", data: { role: "information_cluster" }, position: { x: 0, y: 40 } },
      { id: "source_dashboard", type: "source", label: "Monthly dashboard", data: { sourceId: "source_dashboard", accessStatus: "FETCHED", role: "primary" }, position: { x: 260, y: 0 } },
      { id: "source_minutes", type: "source", label: "Board minutes", data: { sourceId: "source_minutes", accessStatus: "FETCHED", role: "primary" }, position: { x: 260, y: 120 } },
      { id: "source_local_story", type: "source", label: "Metro Ledger story", data: { sourceId: "source_local_story", accessStatus: "FETCHED", role: "secondary" }, position: { x: 560, y: 60 } },
      { id: "source_board_memo", type: "source", label: "Fare memo", data: { sourceId: "source_board_memo", accessStatus: "PAYWALLED", role: "inaccessible" }, position: { x: 260, y: 240 } },
      { id: "snap_dashboard_20260625", type: "snapshot", label: "Dashboard snapshot", data: { sourceId: "source_dashboard", accessStatus: "FETCHED", role: "snapshot" }, position: { x: 420, y: -80 } },
      { id: "snap_minutes_20260625", type: "snapshot", label: "Minutes PDF snapshot", data: { sourceId: "source_minutes", accessStatus: "FETCHED", role: "snapshot" }, position: { x: 420, y: 180 } },
    ],
    edges: [
      { id: "edge_cluster_dashboard", source: "cluster_primary", target: "source_dashboard", label: "origin", data: { relationship: "USES_SAME_DATA", confidence: 0.92, detectionMethod: "metadata and dashboard table id" } },
      { id: "edge_dashboard_story", source: "source_dashboard", target: "source_local_story", label: "cites", data: { relationship: "CITES", confidence: 0.81, detectionMethod: "outbound link and named dashboard" } },
      { id: "edge_minutes_dashboard", source: "source_minutes", target: "source_dashboard", label: "uses same data", data: { relationship: "USES_SAME_DATA", confidence: 0.76, detectionMethod: "shared reporting period and table labels" } },
      { id: "edge_dashboard_snapshot", source: "source_dashboard", target: "snap_dashboard_20260625", label: "snapshot", data: { relationship: "DERIVES_FROM", confidence: 1, detectionMethod: "stored source snapshot id" } },
      { id: "edge_minutes_snapshot", source: "source_minutes", target: "snap_minutes_20260625", label: "snapshot", data: { relationship: "DERIVES_FROM", confidence: 1, detectionMethod: "stored source snapshot id" } },
    ],
  },
};

export const mockedHistory = [
  { runId: mockedRunId, title: mockedReport.title, verdict: mockedReport.verdict, status: mockedReport.status, evidenceReviewedAt: mockedReport.evidenceReviewedAt },
  { runId: "run_mock_quote_001", title: "Quote attribution review", verdict: "Unable to verify exact wording", status: "COMPLETED", evidenceReviewedAt: "2026-06-24T15:07:00-04:00" },
  { runId: "run_mock_article_002", title: "Article claim decomposition", verdict: "Mixed support", status: "COMPLETED", evidenceReviewedAt: "2026-06-22T11:35:00-04:00" },
];
