import { notFound } from "next/navigation";

import { ReportWorkspace } from "@/components/report/report-workspace";
import type { ReportCitation, ReportWorkspaceData, SourcePassage } from "@/lib/report-types";

const reviewedAt = "2026-08-03T18:30:00Z";
const sourceUrl = "https://example.org/transit/fy2025-proposed-budget";

const citations: ReportCitation[] = [
  {
    id: "citation-summary",
    report_section: "summary",
    sentence_text: "The reviewed budget supports an overall funding increase and more frequent weekend service on core lines.",
    passage_id: "passage-budget",
    audit_status: "VERIFIED",
    audit_note: "Citation is accurate and directly supports the sentence.",
  },
  {
    id: "citation-factual",
    report_section: "factual_finding",
    sentence_text: "Weekend rail service is planned at intervals of at least 20 minutes on core lines.",
    passage_id: "passage-budget",
    audit_status: "VERIFIED",
    audit_note: "The stored passage states the planned service interval.",
  },
  {
    id: "citation-attribution",
    report_section: "attribution",
    sentence_text: "Budget documents identify sales-tax revenue as the proposed primary funding source.",
    passage_id: "passage-funding",
    audit_status: "VERIFIED",
    audit_note: "The attribution matches the finance office document.",
  },
  {
    id: "citation-contradiction",
    report_section: "strongest_contradiction",
    sentence_text: "The sales-tax measure had not received final approval at the evidence cutoff.",
    passage_id: "passage-approval",
    audit_status: "VERIFIED",
    audit_note: "The meeting record confirms approval remained pending.",
  },
];

const passages: SourcePassage[] = [
  {
    id: "passage-budget",
    text: "The proposed FY2025 budget increases total transit funding compared with FY2024. The plan invests in more frequent weekend rail service on core lines, with headways of at least 20 minutes.",
    heading_path: "Transit / Service levels",
    page_or_position: "Page 14",
    paragraph_index: 2,
    speaker: null,
    table_ref: null,
    extraction_certainty: 0.98,
    metadata: {},
    citations: citations.filter((citation) => citation.passage_id === "passage-budget"),
  },
  {
    id: "passage-funding",
    text: "The primary proposed funding source for the service expansion is revenue from the regional sales-tax measure.",
    heading_path: "Finance / Proposed revenue",
    page_or_position: "Page 22",
    paragraph_index: 1,
    speaker: null,
    table_ref: "Table 4",
    extraction_certainty: 0.96,
    metadata: {},
    citations: citations.filter((citation) => citation.passage_id === "passage-funding"),
  },
];

const previewData: ReportWorkspaceData = {
  mode: "full",
  run: {
    run_id: "01K1YJQ7EVIDENCEPREVIEW",
    status: "COMPLETED",
    input_type: "CLAIM",
    research_depth: "STANDARD",
    title: "Transit budget and weekend rail service",
    verdict: "Supported with limitations",
    queued_at: reviewedAt,
    started_at: reviewedAt,
    completed_at: reviewedAt,
    failed_at: null,
    cancellation_requested_at: null,
    failure_code: null,
    failure_message: null,
    updated_at: reviewedAt,
    saved_at: null,
    is_owner: true,
  },
  report: {
    run_id: "01K1YJQ7EVIDENCEPREVIEW",
    verdict: "Supported with limitations",
    workspace_scope: "This report evaluates only the submitted claim against the timestamped evidence shown below.",
    scores: {
      article_factual_accuracy: 74,
      attribution_support: 61,
      quote_fidelity: 93,
      context_completeness: 78,
    },
    atomic_claims: [
      {
        id: "claim-budget",
        claim_text: "The proposed transit budget increases total funding compared with FY2024.",
        importance_weight: 1,
        claim_type: "FACTUAL",
        final_label: "SUPPORTED",
        support_score: 88,
        confidence_score: 84,
        context_completeness: 90,
        ambiguities: [],
        gaps: [],
      },
      {
        id: "claim-service",
        claim_text: "Weekend rail service will run at least every 20 minutes on core lines.",
        importance_weight: 0.9,
        claim_type: "FACTUAL",
        final_label: "SUPPORTED",
        support_score: 82,
        confidence_score: 79,
        context_completeness: 76,
        ambiguities: ["The phrase core lines does not include every branch."],
        gaps: ["Headways for non-core lines were not specified."],
      },
      {
        id: "claim-funding",
        claim_text: "The increase is funded primarily through sales-tax revenue.",
        importance_weight: 0.8,
        claim_type: "ATTRIBUTION",
        final_label: "SUPPORTED WITH LIMITATIONS",
        support_score: 64,
        confidence_score: 67,
        context_completeness: 68,
        ambiguities: ["The funding measure was proposed but not finally approved at the cutoff."],
        gaps: [],
      },
    ],
    evidence: [
      {
        id: "evidence-budget",
        atomic_claim_id: "claim-budget",
        passage_id: "passage-budget",
        stance: "STRONGLY_SUPPORTS",
        base_quality: 0.94,
        dependency_multiplier: 1,
        adjusted_weight: 94,
        citation_status: "VERIFIED",
        passage_text: passages[0].text,
        source_title: "FY2025 Proposed Budget",
        source_url: sourceUrl,
        page_or_position: "Page 14",
      },
      {
        id: "evidence-service",
        atomic_claim_id: "claim-service",
        passage_id: "passage-budget",
        stance: "STRONGLY_SUPPORTS",
        base_quality: 0.91,
        dependency_multiplier: 1,
        adjusted_weight: 91,
        citation_status: "VERIFIED",
        passage_text: "The plan invests in more frequent weekend rail service on core lines, with headways of at least 20 minutes.",
        source_title: "FY2025 Proposed Budget",
        source_url: sourceUrl,
        page_or_position: "Page 14",
      },
      {
        id: "evidence-approval",
        atomic_claim_id: "claim-funding",
        passage_id: "passage-approval",
        stance: "PARTIALLY_CONTRADICTS",
        base_quality: 0.89,
        dependency_multiplier: 1,
        adjusted_weight: 89,
        citation_status: "VERIFIED",
        passage_text: "The proposed regional sales-tax measure remained pending final approval at the close of the meeting.",
        source_title: "Regional Board Meeting Record",
        source_url: "https://example.org/transit/board-meeting-record",
        page_or_position: "Agenda item 7",
      },
    ],
    source_graph: {
      nodes: [
        { id: "source-budget", type: "source", label: "FY2025 Proposed Budget", data: {}, position: { x: 80, y: 80 }, metadata: {} },
        { id: "source-board", type: "source", label: "Regional Board Record", data: {}, position: { x: 420, y: 80 }, metadata: {} },
      ],
      edges: [
        { id: "edge-independent", source: "source-budget", target: "source-board", label: "Independent record", relationship: "INDEPENDENT", confidence: 0.92, data: {} },
      ],
    },
    calculations: [
      { id: "calc-factual", atomic_claim_id: null, formula_name: "article_factual_accuracy", formula_text: "Stored server score", inputs: {}, result: { score: 74 }, units: "percent", decimal_context: {}, audit_status: "VERIFIED" },
      { id: "calc-attribution", atomic_claim_id: null, formula_name: "attribution_support", formula_text: "Stored server score", inputs: {}, result: { score: 61 }, units: "percent", decimal_context: {}, audit_status: "VERIFIED" },
      { id: "calc-quote", atomic_claim_id: null, formula_name: "quote_fidelity", formula_text: "Stored server score", inputs: {}, result: { score: 93 }, units: "percent", decimal_context: {}, audit_status: "VERIFIED" },
      { id: "calc-context", atomic_claim_id: null, formula_name: "context_completeness", formula_text: "Stored server score", inputs: {}, result: { score: 78 }, units: "percent", decimal_context: {}, audit_status: "VERIFIED" },
      { id: "calc-confidence", atomic_claim_id: null, formula_name: "verdict_confidence", formula_text: "Stored server calculation", inputs: { coverage: 82, average_quality: 91, independence: 88, consistency: 72, primary_access: 100, penalties: { approval_pending: 12 } }, result: { score: 79 }, units: "percent", decimal_context: {}, audit_status: "VERIFIED" },
      { id: "calc-coverage", atomic_claim_id: null, formula_name: "research_coverage", formula_text: "Stored server calculation", inputs: {}, result: { adequate_evidence: 78, insufficient_evidence: 14, inaccessible_source_impact: 8 }, units: "percent", decimal_context: {}, audit_status: "VERIFIED" },
      { id: "calc-support-budget", atomic_claim_id: "claim-budget", formula_name: "supporting_weight", formula_text: "Stored server calculation", inputs: {}, result: { P: 94 }, units: "weight", decimal_context: {}, audit_status: "VERIFIED" },
      { id: "calc-contradict-budget", atomic_claim_id: "claim-budget", formula_name: "contradicting_weight", formula_text: "Stored server calculation", inputs: {}, result: { N: 0 }, units: "weight", decimal_context: {}, audit_status: "VERIFIED" },
      { id: "calc-support-service", atomic_claim_id: "claim-service", formula_name: "supporting_weight", formula_text: "Stored server calculation", inputs: {}, result: { P: 91 }, units: "weight", decimal_context: {}, audit_status: "VERIFIED" },
      { id: "calc-contradict-service", atomic_claim_id: "claim-service", formula_name: "contradicting_weight", formula_text: "Stored server calculation", inputs: {}, result: { N: 0 }, units: "weight", decimal_context: {}, audit_status: "VERIFIED" },
      { id: "calc-support-funding", atomic_claim_id: "claim-funding", formula_name: "supporting_weight", formula_text: "Stored server calculation", inputs: {}, result: { P: 66 }, units: "weight", decimal_context: {}, audit_status: "VERIFIED" },
      { id: "calc-contradict-funding", atomic_claim_id: "claim-funding", formula_name: "contradicting_weight", formula_text: "Stored server calculation", inputs: {}, result: { N: 34 }, units: "weight", decimal_context: {}, audit_status: "VERIFIED" },
    ],
    methodology_version: "demo-methodology-1.0",
    workflow_version: "demo-workflow-1.0",
    model_versions: { synthesis: "server-configured" },
    prompt_versions: { report: "preview" },
    parser_versions: { html: "preview" },
    retrieval_versions: { search: "preview" },
    score_roles: {
      article_factual_accuracy: "Overall evidence support",
      attribution_support: "Attribution-specific support",
      quote_fidelity: "Quotation accuracy",
      context_completeness: "Surrounding context",
    },
    report_sentences: citations,
    evidence_reviewed_at: reviewedAt,
    generated_at: reviewedAt,
    limitations: [
      "Weekend headways are not specified for every non-core line.",
      "Funding approval timing falls outside the reviewed budget document.",
    ],
  },
  sources: [
    {
      id: "source-budget",
      canonical_url: sourceUrl,
      domain: "example.org",
      title: "FY2025 Proposed Budget",
      author: null,
      publisher: "City Finance Office",
      source_type: "PRIMARY",
      content_type: "text/html",
      role: "PRIMARY",
      retrieval_reason: "Official budget document",
      inaccessible_reason: null,
      snapshot_id: "snapshot-budget-v2",
      snapshot_version: 2,
      access_status: "FETCHED",
      retrieved_at: reviewedAt,
      published_at: "2026-07-20T16:00:00Z",
      content_hash: "preview-budget-hash",
      parser_name: "html",
      parser_version: "preview",
      correction_status: "CORRECTED",
      correction_history: [{ snapshot_id: "snapshot-budget-v2", snapshot_version: 2, status: "CORRECTED", retrieved_at: reviewedAt }],
      snapshot_metadata: {},
      failure_reason: null,
      passages,
    },
    {
      id: "source-board",
      canonical_url: "https://example.org/transit/board-meeting-record",
      domain: "example.org",
      title: "Regional Board Meeting Record",
      author: null,
      publisher: "Regional Transit Board",
      source_type: "PRIMARY",
      content_type: "text/html",
      role: "CONTRADICTING",
      retrieval_reason: "Official approval record",
      inaccessible_reason: null,
      snapshot_id: "snapshot-board-v1",
      snapshot_version: 1,
      access_status: "FETCHED",
      retrieved_at: reviewedAt,
      published_at: "2026-08-01T16:00:00Z",
      content_hash: "preview-board-hash",
      parser_name: "html",
      parser_version: "preview",
      correction_status: null,
      correction_history: [],
      snapshot_metadata: {},
      failure_reason: null,
      passages: [
        {
          id: "passage-approval",
          text: "The proposed regional sales-tax measure remained pending final approval at the close of the meeting.",
          heading_path: "Agenda / Funding measure",
          page_or_position: "Agenda item 7",
          paragraph_index: 3,
          speaker: "Board secretary",
          table_ref: null,
          extraction_certainty: 0.97,
          metadata: {},
          citations: citations.filter((citation) => citation.passage_id === "passage-approval"),
        },
      ],
    },
  ],
  sourceGraph: {
    nodes: [
      { id: "source-budget", type: "source", label: "FY2025 Proposed Budget", data: {}, position: { x: 80, y: 80 }, metadata: {} },
      { id: "source-board", type: "source", label: "Regional Board Record", data: {}, position: { x: 420, y: 80 }, metadata: {} },
    ],
    edges: [
      { id: "edge-independent", source: "source-budget", target: "source-board", label: "Independent record", relationship: "INDEPENDENT", confidence: 0.92, data: {} },
    ],
  },
};

export default function ReportUiPreviewPage() {
  if (process.env.NODE_ENV === "production") notFound();

  return <ReportWorkspace data={previewData} />;
}
